In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import tensorflow as tf
from tensorflow.keras.preprocessing.image import img_to_array
import cv2 as cv2
from PIL import Image
import os
import np_utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [78]:
df_par = os.listdir("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Parasitized")
df_par[:10]

['C100P61ThinF_IMG_20150918_144104_cell_162.png',
 'C100P61ThinF_IMG_20150918_144104_cell_163.png',
 'C100P61ThinF_IMG_20150918_144104_cell_164.png',
 'C100P61ThinF_IMG_20150918_144104_cell_165.png',
 'C100P61ThinF_IMG_20150918_144104_cell_166.png',
 'C100P61ThinF_IMG_20150918_144104_cell_167.png',
 'C100P61ThinF_IMG_20150918_144104_cell_168.png',
 'C100P61ThinF_IMG_20150918_144104_cell_169.png',
 'C100P61ThinF_IMG_20150918_144104_cell_170.png',
 'C100P61ThinF_IMG_20150918_144104_cell_171.png']

In [79]:
df_npar = os.listdir("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Uninfected")
df_npar[:10]

['C100P61ThinF_IMG_20150918_144104_cell_128.png',
 'C100P61ThinF_IMG_20150918_144104_cell_131.png',
 'C100P61ThinF_IMG_20150918_144104_cell_144.png',
 'C100P61ThinF_IMG_20150918_144104_cell_21.png',
 'C100P61ThinF_IMG_20150918_144104_cell_25.png',
 'C100P61ThinF_IMG_20150918_144104_cell_34.png',
 'C100P61ThinF_IMG_20150918_144104_cell_48.png',
 'C100P61ThinF_IMG_20150918_144104_cell_65.png',
 'C100P61ThinF_IMG_20150918_144348_cell_108.png',
 'C100P61ThinF_IMG_20150918_144348_cell_120.png']

In [80]:
df=[]
labels=[]
for img in df_par:
    img_rr=mp.imread("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Parasitized//"+img)
    img_resize = cv2.resize(img_rr, (50,50))
    img_arr = img_to_array(img_resize)
    df.append(img_arr)
    labels.append(1)

In [82]:
np.array(df)

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [17]:
img_read = mp.imread("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Uninfected/"+df_npar[0])
img_size = cv2.resize(img_read, (50,50))
img_size.size, img_read.size

(7500, 66720)

In [22]:
df_2=[]
labels_2=[]
for img in df_npar:
    img_read = mp.imread("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Uninfected/"+img)
    img_resize=cv2.resize(img_read, (50,50))
    img_array = img_to_array(img_resize)
    labels_2.append(1)
    df_2.append(img_array)

In [24]:
for i in range(len(df_2)):
    print(df_2[i].shape)

(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50, 50, 3)
(50,

In [81]:
for img in df_npar:
    img_read = mp.imread("C:/Users/KIIT/Desktop/ch/Python/malaria/cell_images/cell_images/Uninfected/"+img)
    img_resize=cv2.resize(img_read, (50,50))
    img_array = img_to_array(img_resize)
    labels.append(0)
    df.append(img_array)

In [31]:
type(df)

list

In [84]:
df_new = np.array(df)

In [86]:
type(df_new)

numpy.ndarray

In [83]:
labels = np.array(labels)

In [87]:
a = np.arange(df_new.shape[0])
np.random.shuffle(a)
a

array([ 8043, 18449, 25140, ...,  5266, 12631,  3484])

In [88]:
df_new = df_new[a]
labels = labels[a]

In [121]:
x_train, x_test, y_train, y_test = train_test_split(df_new, labels, test_size=0.2, random_state = 101)

In [122]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((22046, 50, 50, 3), (22046,), (5512, 50, 50, 3), (5512,))

In [124]:
y_test = tf.keras.utils.to_categorical(y_test , num_classes=2)
y_train_2.shape, y_test.shape

((22046, 2), (5512, 2))

In [123]:
y_train_2 = keras.utils.to_categorical(y_train, num_classes=2)
y_train_2.shape

(22046, 2)

In [54]:
y_train, y_test

(array([[[0., 1.],
         [1., 0.]],
 
        [[0., 1.],
         [1., 0.]],
 
        [[1., 0.],
         [0., 1.]],
 
        ...,
 
        [[1., 0.],
         [0., 1.]],
 
        [[1., 0.],
         [0., 1.]],
 
        [[1., 0.],
         [0., 1.]]], dtype=float32),
 array([[0., 1.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32))

In [125]:
x_train.shape, y_train_2.shape, x_test.shape, y_test.shape

((22046, 50, 50, 3), (22046, 2), (5512, 50, 50, 3), (5512, 2))

In [126]:
import keras
from keras.layers import Dense, Conv2D
from keras.layers import MaxPooling2D, Activation, BatchNormalization, Dropout, Flatten
from keras.models import Sequential
from keras import backend as K
from keras import optimizers

In [140]:
def CNNb(h, w, c):
    model = Sequential()
    ipshape = (h, w, c)
    chandim = -1
    model.add(Conv2D(64, (3,3), activation='relu', input_shape = ipshape))
    model.add(MaxPooling2D(2, 2))
    model.add(BatchNormalization(axis=chandim))
    model.add(Dropout(0.2))
    
    model.add(Conv2D(64, (3,3), activation='relu', input_shape = ipshape ))
    model.add(MaxPooling2D(2,2))
    model.add(BatchNormalization(axis=chandim))
    model.add(Dropout(0.2))
    
    model.add(Conv2D(32, (3,3), activation='relu', input_shape=ipshape))
    model.add(MaxPooling2D(2,2))
    model.add(BatchNormalization(axis=chandim))
    model.add(Dropout(0.2))
    
    model.add(Flatten())
    
    model.add(Dense(512, activation='relu'))
    model.add(BatchNormalization(axis=chandim))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation='softmax'))
    
    return model

In [128]:
emodel = CNNb(h=50,w=50,c=3)
emodel.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 48, 48, 32)        896       
                                                                 
 max_pooling2d_11 (MaxPoolin  (None, 24, 24, 32)       0         
 g2D)                                                            
                                                                 
 batch_normalization_13 (Bat  (None, 24, 24, 32)       128       
 chNormalization)                                                
                                                                 
 dropout_13 (Dropout)        (None, 24, 24, 32)        0         
                                                                 
 conv2d_13 (Conv2D)          (None, 22, 22, 32)        9248      
                                                                 
 max_pooling2d_12 (MaxPoolin  (None, 11, 11, 32)      

In [130]:
emodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
h=emodel.fit(x_train, y_train_2, epochs=20, batch_size=32)

Epoch 1/20
689/689 [==============================] - 336s 484ms/step - loss: 0.5165 - accuracy: 0.7871
Epoch 2/20
689/689 [==============================] - 305s 443ms/step - loss: 0.2110 - accuracy: 0.9232
Epoch 3/20
689/689 [==============================] - 3276s 5s/step - loss: 0.1851 - accuracy: 0.9340
Epoch 4/20
689/689 [==============================] - 425s 617ms/step - loss: 0.1709 - accuracy: 0.9435
Epoch 5/20
689/689 [==============================] - 341s 495ms/step - loss: 0.1688 - accuracy: 0.9442
Epoch 6/20
689/689 [==============================] - 343s 497ms/step - loss: 0.1640 - accuracy: 0.9455
Epoch 7/20
689/689 [==============================] - 347s 504ms/step - loss: 0.1606 - accuracy: 0.9466
Epoch 8/20
689/689 [==============================] - 333s 483ms/step - loss: 0.1528 - accuracy: 0.9519
Epoch 9/20
689/689 [==============================] - 329s 477ms/step - loss: 0.1499 - accuracy: 0.9496
Epoch 10/20
689/689 [==============================] - 309s 448ms/

In [137]:
y_pred = emodel.evaluate(x_test, y_test)

173/173 [==============================] - 22s 127ms/step - loss: 0.1555 - accuracy: 0.9559


In [139]:
print("Loss :",y_pred[0])
print("Accuracy :",y_pred[1])

Loss : 0.15549759566783905
Accuracy : 0.9559143781661987


In [141]:
emodel2 = CNNb(h=50, w=50, c=3)
emodel2.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_15 (Conv2D)          (None, 48, 48, 64)        1792      
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 24, 24, 64)       0         
 g2D)                                                            
                                                                 
 batch_normalization_17 (Bat  (None, 24, 24, 64)       256       
 chNormalization)                                                
                                                                 
 dropout_17 (Dropout)        (None, 24, 24, 64)        0         
                                                                 
 conv2d_16 (Conv2D)          (None, 22, 22, 64)        36928     
                                                                 
 max_pooling2d_15 (MaxPoolin  (None, 11, 11, 64)      

In [ ]:
emodel2.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
h=emodel2.fit(x_train, y_train_2, epochs=20, batch_size=32)

Epoch 1/20
689/689 [==============================] - 452s 654ms/step - loss: 0.1971 - accuracy: 0.9339
Epoch 2/20
689/689 [==============================] - 450s 653ms/step - loss: 0.1746 - accuracy: 0.9439
Epoch 3/20
689/689 [==============================] - 450s 653ms/step - loss: 0.1676 - accuracy: 0.9455
Epoch 4/20
689/689 [==============================] - 450s 654ms/step - loss: 0.1629 - accuracy: 0.9487
Epoch 5/20
689/689 [==============================] - 451s 655ms/step - loss: 0.1560 - accuracy: 0.9508
Epoch 6/20
689/689 [==============================] - 29198s 42s/step - loss: 0.1532 - accuracy: 0.9511
Epoch 7/20
689/689 [==============================] - 494s 716ms/step - loss: 0.1491 - accuracy: 0.9534
Epoch 8/20
263/689 [==========>...................] - ETA: 4:57 - loss: 0.1469 - accuracy: 0.9488